version: '3.9'
services:
  app:
    image: harmonica_l12_node
    build: .
    restart: always
    environment:
      HL12N_ROUTER_URL: ${HL12N_ROUTER_URL:?}
      HL12N_OUTPUT_TIMEZONE: ${HL12N_OUTPUT_TIMEZONE:?}
      HL12N_OUTPUT_INTERVAL: ${HL12N_OUTPUT_INTERVAL:?}
      HL12N_API_URL: ${HL12N_API_URL:?}
      HL12N_API_TOKEN: ${HL12N_API_TOKEN:?}
      HL12N_TIMEOUT: ${HL12N_TIMEOUT:?}
