version: '3.9'
services:
  app:
    image: harmonica_l12_node
    build: .
    restart: always
    environment:
      ROUTER_URL: ${ROUTER_URL:?}
      OUTPUT_TIMEZONE: ${OUTPUT_TIMEZONE:?}
      OUTPUT_INTERVAL: ${OUTPUT_INTERVAL:?}
      API_URL: ${API_URL:?}
      API_TOKEN: ${API_TOKEN:?}
